
schema: "https://json-schema.org/draft/2020-12/schema"
baseURI: "${MTT_SERVER_URL}/generated/schemas/telematics"
specializationStyle: INHERITANCE_ALL_OF # Choice between: COMPOSITION, INHERITANCE_INCLUDE, INHERITANCE_ALL_OF
contentType: "application/schema+json"
fileType: "schema.json"

