schema: "https://json-schema.org/draft/2020-12/schema"
#baseURI: "https://apigeneration.tech/schemas/reversed"
baseURI: "${MTT_SERVER_URL}/schemas"
specFileType: "schema.json"
specializationStyle: INHERITANCE_ALL_OF # Choice between: COMPOSITION, INHERITANCE_INCLUDE, INHERITANCE_ALL_OF
dependencies:
  "Base Type":
    modelFileUrl: "file:/reversed-generator/generated/mtt-models/reversed-base.json"
    version: "1.0.0"

